export const ADD_EVENT_REQUEST="ADD_EVENT_REQUEST"
export const ADD_EVENT_SUCCESS="ADD_EVENT_SUCCESS"
export const ADD_EVENT_FAIL="ADD_EVENT_FAIL"

//  get Event Data

export const GET_EVENT_REQUEST="GET_EVENT_REQUEST"
export const GET_EVENT_SUCCESS="GET_EVENT_SUCCESS"
export const GET_EVENT_FAIL="GET_EVENT_FAIL"